AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus HTTP - person-resource-1.0.0-SNAPSHOT
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"

Resources:
  PersonResourceNative:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtimei
      Runtime: provided.al2023
      CodeUri: ../target/function.zip
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaDynamoDBExecutionRole
        - AmazonDynamoDBFullAccess
      Timeout: 15
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
      Events:
        HttpApiEvent:
          Type: HttpApi

Outputs:
  PersonResourceNativeApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
    Export:
      Name: PersonResourceNativeApi
